In [1]:
import pandas as pd

#Load crime dataset
crime = pd.read_csv('../data/raw/crime.csv')

#First Look at Data
print(crime.shape)
print(crime.columns.tolist())

(251284, 17)
['INCIDENT_NUMBER', 'OFFENSE_CODE', 'OFFENSE_CODE_GROUP', 'OFFENSE_DESCRIPTION', 'DISTRICT', 'REPORTING_AREA', 'SHOOTING', 'OCCURRED_ON_DATE', 'YEAR', 'MONTH', 'DAY_OF_WEEK', 'HOUR', 'UCR_PART', 'STREET', 'Lat', 'Long', 'Location']

C:\Users\josen\AppData\Local\Temp\ipykernel_8976\355981248.py:4: DtypeWarning: Columns (0: INCIDENT_NUMBER) have mixed types. Specify dtype option on import or set low_memory=False.
  crime = pd.read_csv('../data/raw/crime.csv')

In [2]:
crime.isnull().sum()

INCIDENT_NUMBER             0
OFFENSE_CODE                0
OFFENSE_CODE_GROUP     251284
OFFENSE_DESCRIPTION         0
DISTRICT                  487
REPORTING_AREA          30614
SHOOTING                    0
OCCURRED_ON_DATE            0
YEAR                        0
MONTH                       0
DAY_OF_WEEK                 0
HOUR                        0
UCR_PART               251284
STREET                      0
Lat                     14837
Long                    14837
Location                14837
dtype: int64

In [7]:
crime.columns.tolist()

['INCIDENT_NUMBER',
 'OFFENSE_CODE',
 'OFFENSE_DESCRIPTION',
 'DISTRICT',
 'REPORTING_AREA',
 'SHOOTING',
 'OCCURRED_ON_DATE',
 'YEAR',
 'MONTH',
 'DAY_OF_WEEK',
 'HOUR',
 'STREET',
 'Lat',
 'Long',
 'Location']

In [8]:
print(crime.shape)
crime.isnull().sum()

(236447, 15)

INCIDENT_NUMBER            0
OFFENSE_CODE               0
OFFENSE_DESCRIPTION        0
DISTRICT                 123
REPORTING_AREA         28519
SHOOTING                   0
OCCURRED_ON_DATE           0
YEAR                       0
MONTH                      0
DAY_OF_WEEK                0
HOUR                       0
STREET                     0
Lat                        0
Long                       0
Location                   0
dtype: int64

In [16]:
crime = crime.drop(columns=['INCIDENT_NUMBER', 'OFFENSE_CODE', 'REPORTING_AREA', 'STREET', 'DAY_OF_WEEK', 'HOUR', 'Location', 'YEAR', 'MONTH'])

KeyError: "['INCIDENT_NUMBER', 'OFFENSE_CODE', 'REPORTING_AREA', 'STREET', 'DAY_OF_WEEK', 'HOUR', 'Location'] not found in axis"

In [11]:
print(crime.shape)
crime.head()

(236447, 8)

,OFFENSE_DESCRIPTION,DISTRICT,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,Lat,Long
0,INVESTIGATE PERSON,B3,0,2023-01-27 22:44:00+00,2023,1,42.271661,-71.099534
1,VERBAL DISPUTE,B2,0,2023-01-17 20:21:00+00,2023,1,42.312597,-71.092875
2,INVESTIGATE PERSON,A1,0,2023-01-24 00:00:00+00,2023,1,42.365700,-71.052892
3,INVESTIGATE PROPERTY,B3,0,2023-03-31 17:14:00+00,2023,3,42.292788,-71.088519
4,ASSAULT - AGGRAVATED,B2,0,2023-01-26 09:00:00+00,2023,1,42.310269,-71.089310

In [14]:
crime = crime[crime['YEAR'] >= 2021]
print(crime.shape)

(236447, 8)

In [15]:
crime['YEAR'].value_counts().sort_index()

YEAR
2023    72713
2024    74732
2025    76395
2026    12607
Name: count, dtype: int64

In [17]:
crime = crime.drop(columns=['YEAR', 'MONTH'])
print(crime.shape)
crime.head()

(236447, 6)

,OFFENSE_DESCRIPTION,DISTRICT,SHOOTING,OCCURRED_ON_DATE,Lat,Long
0,INVESTIGATE PERSON,B3,0,2023-01-27 22:44:00+00,42.271661,-71.099534
1,VERBAL DISPUTE,B2,0,2023-01-17 20:21:00+00,42.312597,-71.092875
2,INVESTIGATE PERSON,A1,0,2023-01-24 00:00:00+00,42.365700,-71.052892
3,INVESTIGATE PROPERTY,B3,0,2023-03-31 17:14:00+00,42.292788,-71.088519
4,ASSAULT - AGGRAVATED,B2,0,2023-01-26 09:00:00+00,42.310269,-71.089310

In [18]:
crime.to_csv('../data/processed/crime_clean.csv', index=False)